export const GET_RESTAURANT_START = 'GET_RESTAURANT_START'
export const GET_RESTAURANT_SUCCESS = 'GET_RESTAURANT_SUCCESS'
export const GET_RESTAURANT_FAIL = 'GET_RESTAURANT_FAIL'

export const POST_RESTAURANT_START = 'POST_RESTAURANT_START'
export const POST_RESTAURANT_SUCCESS = 'POST_RESTAURANT_SUCCESS'
export const POST_RESTAURANT_FAIL = 'POST_RESTAURANT_FAIL'

export const CLEAR_RESTAURANT = 'CLEAR_RESTAURANT'

export const POST_TABLE_START = 'POST_TABLE_START'
export const POST_TABLE_SUCCESS = 'POST_TABLE_SUCCESS'
export const POST_TABLE_FAIL = 'POST_TABLE_FAIL'

export const DELETE_TABLE_START = 'DELETE_TABLE_START'
export const DELETE_TABLE_SUCCESS = 'DELETE_TABLE_SUCCESS'
export const DELETE_TABLE_FAIL = 'DELETE_TABLE_FAIL'

export const GET_TABLES_START = 'GET_TABLES_START'
export const GET_TABLES_SUCCESS = 'GET_TABLES_SUCCESS'
export const GET_TABLES_FAIL = 'GET_TABLES_FAIL'

export const SET_CURRENT_USER = 'SET_CURRENT_USER'
export const GOOGLE_SIGN_IN_START = 'GOOGLE_SIGN_IN_START'
export const EMAIL_SIGN_IN_START = 'EMAIL_SIGN_IN_START'
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS'
export const SIGN_IN_FAILURE = 'SIGN_IN_FAILURE'
export const CHECK_USER_SESSION = 'CHECK_USER_SESSION'
export const SIGN_OUT_START = 'SIGN_OUT_START'
export const SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS'
export const SIGN_OUT_FAILURE = 'SIGN_OUT_FAILURE'
export const SIGN_UP_START = 'SIGN_UP_START'
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS'
export const SIGN_UP_FAILURE = 'SIGN_UP_FAILURE'
