export const GET_RESTAURANT_START = 'GET_RESTAURANT_START'
export const GET_RESTAURANT_SUCCESS = 'GET_RESTAURANT_SUCCESS'
export const GET_RESTAURANT_FAIL = 'GET_RESTAURANT_FAIL'

export const POST_RESTAURANT_START = 'POST_RESTAURANT_START'
export const POST_RESTAURANT_SUCCESS = 'POST_RESTAURANT_SUCCESS'
export const POST_RESTAURANT_FAIL = 'POST_RESTAURANT_FAIL'

export const CLEAR_RESTAURANT = 'CLEAR_RESTAURANT'

export const PERSIST_TABLES_START = 'PERSIST_TABLES_START'
export const PERSIST_TABLES_SUCCESS = 'PERSIST_TABLES_SUCCESS'
export const PERSIST_TABLES_FAIL = 'PERSIST_TABLES_FAIL'

export const DELETE_TABLE_START = 'DELETE_TABLE_START'
export const DELETE_TABLE_SUCCESS = 'DELETE_TABLE_SUCCESS'
export const DELETE_TABLE_FAIL = 'DELETE_TABLE_FAIL'

export const SELECT_TABLE = 'SELECT_TABLE'
export const TOGGLE_LAYOUT_SWITCH = 'TOGGLE_LAYOUT_SWITCH'

export const MARK_TRIED = 'MARK_TRIED'

export const GET_RESERVATIONS_START = 'GET_RESERVATIONS_START'
export const GET_RESERVATIONS_SUCCESS = 'GET_RESERVATIONS_SUCCESS'
export const GET_RESERVATIONS_FAIL = 'GET_RESERVATIONS_FAIL'

export const PERSIST_RESERVATIONS_START = 'PERSIST_RESERVATIONS_START'
export const PERSIST_RESERVATIONS_SUCCESS = 'PERSIST_RESERVATIONS_SUCCESS'
export const PERSIST_RESERVATIONS_FAIL = 'PERSIST_RESERVATIONS_FAIL'

export const OPEN_RESERVATIONS_DIALOG = 'OPEN_RESERVATIONS_DIALOG'
export const CLOSE_RESERVATIONS_DIALOG = 'CLOSE_RESERVATIONS_DIALOG'
export const SET_RESERVATIONS_FILTER = 'SET_RESERVATIONS_FILTER'

export const CLEAR_RESTAURANT_ERROR = 'CLEAR_RESTAURANT_ERROR'
export const CLEAR_USER_ERROR = 'CLEAR_USER_ERROR'

export const SET_CURRENT_USER = 'SET_CURRENT_USER'
export const GOOGLE_SIGN_IN_START = 'GOOGLE_SIGN_IN_START'
export const EMAIL_SIGN_IN_START = 'EMAIL_SIGN_IN_START'
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS'
export const SIGN_IN_FAILURE = 'SIGN_IN_FAILURE'
export const CHECK_USER_SESSION = 'CHECK_USER_SESSION'
export const SIGN_OUT_START = 'SIGN_OUT_START'
export const SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS'
export const SIGN_OUT_FAILURE = 'SIGN_OUT_FAILURE'
export const SIGN_UP_START = 'SIGN_UP_START'
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS'
export const SIGN_UP_FAILURE = 'SIGN_UP_FAILURE'
